// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ2IhNp3m92bFo38J7z3JIui8UHRLT6zA',
    appId: '1:354777758569:web:9ccb027375d71f463d5bf8',
    messagingSenderId: '354777758569',
    projectId: 'scmu-6f1b8',
    authDomain: 'scmu-6f1b8.firebaseapp.com',
    databaseURL: 'https://scmu-6f1b8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-6f1b8.firebasestorage.app',
    measurementId: 'G-P909LKCWNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXgCMDv2eyZh0Zuybv2Dsww1FwqFIAZx0',
    appId: '1:354777758569:android:b15d8efb8e5d6d4e3d5bf8',
    messagingSenderId: '354777758569',
    projectId: 'scmu-6f1b8',
    databaseURL: 'https://scmu-6f1b8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-6f1b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgqKCJNotoq3WkPu5HjxeliRJF04OfiFE',
    appId: '1:354777758569:ios:87412b703fa967c03d5bf8',
    messagingSenderId: '354777758569',
    projectId: 'scmu-6f1b8',
    databaseURL: 'https://scmu-6f1b8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-6f1b8.firebasestorage.app',
    iosBundleId: 'com.example.irrigApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgqKCJNotoq3WkPu5HjxeliRJF04OfiFE',
    appId: '1:354777758569:ios:87412b703fa967c03d5bf8',
    messagingSenderId: '354777758569',
    projectId: 'scmu-6f1b8',
    databaseURL: 'https://scmu-6f1b8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-6f1b8.firebasestorage.app',
    iosBundleId: 'com.example.irrigApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ2IhNp3m92bFo38J7z3JIui8UHRLT6zA',
    appId: '1:354777758569:web:990958057de263f03d5bf8',
    messagingSenderId: '354777758569',
    projectId: 'scmu-6f1b8',
    authDomain: 'scmu-6f1b8.firebaseapp.com',
    databaseURL: 'https://scmu-6f1b8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-6f1b8.firebasestorage.app',
    measurementId: 'G-W6N96895W5',
  );

}